### PR TITLE
Call custom code from migration script

### PR DESCRIPTION
**Pull request by rPraml**
Hello Rob,

we often have complex migration tasks that could probably be better solved with java code (complex recomputations or just quoting a string to JSON)

We struggled last time, as we tried to convert a text field to a json field `"hello World"` -> `{"text":"\"hello World\""}` which leads into a "replace hell" as the DB did not have a JSON_QUOTE function.

With this code, we can register a CustomStatementHandler, that can e.g. call javascript, groovy or just shell commands.

I provided one example, where I simply call a static method from javascript.

What do you think about this change?

### CODE REVIEW

**Comment by rbygrave** [comment]
I feel the 90% case is more like calling a method in the application code.  My gut says there is a bit too much flexibility here and hence we are leaving too much plumbing code up to the users to write. 

In my head I have something more like ... create a 'context' that contains the connection, type/method and arguments.  This is then sent to registered listeners which can process it.

That is, the application (that invokes the migration runner) can wire/register "custom migration listener" ... ideally support wrapping the jdbc connection as a Ebean transaction ... and make it easy to write migration logic using Ebean features.

I guess this isn't too different to what you have. 

I feel the simple case should be simpler if possible (we do the plumbing rather than the users of the migration runner).
- Implement some Java interface, register it somehow
- some well known format of java:org.some.package.SomeType.someMethod(arg1, arg2);
- Maybe provide an abstract class to help e.g. wrap connection into Ebean transaction

I'll do some more thinking ...

**Comment by rbygrave** [comment]
```sql
alter table m1 add column addcol varchar(10);

custom: someKey arg1 arg2 arg3

...
```
- Have a Java interface    
```java
interface CustomMigration {
  void process(CustomMigrationContext migrationContext);
}

class CustomMigrationContext {
  String key;
  String[] args;
  Connection connection;
}
```
Register the custom migration instances with the runner ...
```
register(String key, CustomMigration custom);
```
Hmmm.

**Comment by rPraml** [comment]
Hello Rob,
I've updated the PR, you can now register your CustomCommandHandler in the CustomMigrationConfig.

There are also 3 default Implementations included which should cover >90% of the use cases:
- call a static method
- call a spring bean
- do some debug logging
(Unfortunately, I need some "argument parser" and this takes about the half of this code, that's why I used javascript in the first example)
If you say, it's the application's task to provide an according handler implementation, it would be OK for me to remove the parser etc.

**Comment by rPraml** [comment]
I close this. #46 should fit our needs.

**Pull request closed without merging**
